"""Initial migration with User, Post, and Tag models

Revision ID: 8f387d571778
Revises: 
Create Date: 2025-05-14 14:48:24.159629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f387d571778'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the column as nullable first
    op.add_column('post', sa.Column('deleted', sa.Boolean(), nullable=True))
    
    # Step 2: Update existing rows to set deleted = False
    op.execute("UPDATE post SET deleted = FALSE")
    
    # Step 3: Set the column to NOT NULL with a default value
    op.alter_column('post', 'deleted', 
                   nullable=False,
                   server_default=sa.sql.expression.literal(False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Simply drop the column when downgrading
    op.drop_column('post', 'deleted')
    # ### end Alembic commands ###
