"""Add referral system tables and user fields

Revision ID: d97eedcac203
Revises: 8f387d571778
Create Date: 2025-06-01 10:41:38.154946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd97eedcac203'
down_revision: Union[str, None] = '8f387d571778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_users_hashed_google_id', table_name='waitlist_users')
    op.drop_table('waitlist_users')
    op.alter_column('referral_codes', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.add_column('user', sa.Column('referral_code', sa.VARCHAR(length=8), nullable=True))
    op.add_column('user', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('referral_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint(None, 'user', ['referral_code'])
    op.create_foreign_key(None, 'user', 'user', ['referred_by'], ['id'])
    op.drop_column('user', 'is_wait_listed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_wait_listed', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'referral_count')
    op.drop_column('user', 'referred_by')
    op.drop_column('user', 'referral_code')
    op.alter_column('referral_codes', 'code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_table('waitlist_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hashed_google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waitlist_users_pkey')
    )
    op.create_index('ix_waitlist_users_hashed_google_id', 'waitlist_users', ['hashed_google_id'], unique=True)
    # ### end Alembic commands ###
